name: Mobile App Automation

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  android-test:
    runs-on: macos-latest # Apple M1/M2 (ARM Architecture)
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true 

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Appium and Dependencies
        run: |
          npm i -g appium
          appium driver install uiautomator2
          pip install Appium-Python-Client
          appium & 

      - name: Run Android Emulator and Execute Script
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30 # ARM ke liye API 30 zyada stable hai
          target: google_apis
          arch: arm64-v8a # <--- YEH HAI GAME CHANGER (Mobile wala architecture)
          profile: Nexus 6
          disable-animations: true
          script: |
            echo "Checking APK files..."
            ls -lh SportsAppAuto/apks/
            
            echo "Installing Split APKs..."
            adb install-multiple SportsAppAuto/apks/base.apk SportsAppAuto/apks/split_config.arm64_v8a.apk SportsAppAuto/apks/split_config.en.apk SportsAppAuto/apks/split_config.xxhdpi.apk
            
            echo "Running Python Script..."
            cd SportsAppAuto && python automation.py

      - name: Upload Screenshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: App-Screenshots
          path: SportsAppAuto/*.png
