name: Mobile App Automation

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  android-test:
    # Yahan humne macOS ko hata kar Ubuntu laga diya hai (Fauran start hoga)
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true 

      # Ubuntu par KVM (Hardware Acceleration) enable karna zaroori hota hai emulator ke liye
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Appium and Dependencies
        run: |
          npm i -g appium
          appium driver install uiautomator2
          pip install Appium-Python-Client
          appium & 

      - name: Run Android Emulator and Execute Script
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          script: |
            cd SportsAppAuto
            
            echo "Checking APK files..."
            ls -lh apks/
            
            echo "Installing Split APKs..."
            adb install-multiple apks/base.apk apks/split_config.arm64_v8a.apk apks/split_config.en.apk apks/split_config.xxhdpi.apk
            
            echo "Running Python Script..."
            python automation.py

      - name: Upload Screenshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: App-Screenshots
          path: SportsAppAuto/*.png
